# Generated by Django 4.2.5 on 2024-05-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nivel0', '0001_initial'),
        ('nivel4', '0001_initial'),
        ('nivel2', '0001_initial'),
        ('nivel1', '0001_initial'),
        ('nivel5', '0001_initial'),
        ('nivel3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nivel1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel1', to='nivel1.nivel1')),
                ('nivel2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel2', to='nivel2.nivel2')),
                ('nivel3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel3', to='nivel3.nivel3')),
                ('nivel4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel4', to='nivel4.nivel4')),
                ('nivel5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nivel5', to='nivel5.nivel5')),
                ('plano_fin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel0', to='nivel0.nivel0')),
            ],
        ),
    ]
